#!/bin/bash
set -e

# Raspberry Pi auto update script
# Runar Ovesen Hjerpbakk
# https://hjerpbakk.com
# 
# Usage: 
# $ ./any_raspbian
#
# Run from GitHub:
# $ curl -s https://raw.githubusercontent.com/Sankra/dotfiles/master/roles/any_raspbian | sh

echo "Adding automatic updates to crontab"

if crontab -l | grep -q "sudo apt -y update"; 
then 
  echo "Auto update of package list already exists in crontab"
else
  echo "Adding auto update of package list to crontab"
  (crontab -l 2>/dev/null; echo "0 3 * * * sudo apt -y update"); echo | crontab - 
fi

if crontab -l | grep -q "sudo apt -y dist-upgrade"; 
then 
  echo "Upgrade of installed packages already exists in crontab"
else
  echo "Adding upgrade of installed packages"
  (crontab -l 2>/dev/null; echo "0 4 * * * sudo apt -y dist-upgrade"); echo | crontab - 
fi

echo "Installation complete. Enjoy!"

