#!/bin/bash
set -e

# Raspberry Pi auto update script
# Runar Ovesen Hjerpbakk
# https://hjerpbakk.com
# 
# Usage: $ ./any_raspbian
#
# Net install:
#   $ curl https://raw.githubusercontent.com/Sankra/dotfiles/master/roles/any_raspbian | sh

if crontab -l | grep -q "sudo apt -y update"; 
then 
  echo "Auto update of package list already exists in crontab"
else
  echo "Installing auto update of package list"
  crontab -l | grep -v '^$' | crontab -
  (crontab -l 2>/dev/null; echo "0 3 * * * sudo apt -y update"); echo | crontab - 
fi
echo

crontab -l

echo
echo "Installation complete. Enjoy!"

