#!/bin/bash

# Raspberry Pi script for removing packages not needed when running headless
# Runar Ovesen Hjerpbakk
# https://hjerpbakk.com
# Inspired by https://github.com/karaage0703/raspberry-pi-setup/blob/master/shrink-raspbian-stretch_jessie.sh
# 
# Usage: 
# $ sudo ./shrink-raspbian
#
# Run from GitHub:
# $ curl -s https://raw.githubusercontent.com/Sankra/dotfiles/master/tasks/shrink-raspbian | sudo sh

# Must be run as root or sudo
if [ $(id -u) != 0 ]
then
  echo "This script must be run as root or with sudo."
  exit
fi

# delete package
delete_package(){
	# delete package
	apt autoremove -y wolfram-engine
	apt autoremove -y oracle-java8-jdk
	apt autoremove -y sonic-pi
	apt autoremove -y libreoffice*
	# 100MB-----------
	apt autoremove -y scratch* nuscratch squeak-plugins-scratch
	apt autoremove -y nuscratch
	apt autoremove -y gnome-user-guide
	apt autoremove -y freepats
	apt autoremove -y libraspberrypi-doc
	apt autoremove -y pypy
	apt autoremove -y greenfoot
	# 10MB-----------
	apt autoremove -y epiphany-browser*
	apt autoremove -y bluej
	apt autoremove -y netsurf*
	apt autoremove -y supercollider-server
	apt autoremove -y debian-reference*
	apt autoremove -y minecraft-pi
	apt autoremove -y claws-mail
	apt autoremove -y galculator
	apt autoremove -y geany*
	apt autoremove -y idle*
	apt autoremove -y lxterminal
	apt autoremove -y
	apt clean -y
}

START_TIME=`date +%s`

# change directory here
cd `dirname $0`

delete_package

END_TIME=`date +%s`

SS=`expr ${END_TIME} - ${START_TIME}`
HH=`expr ${SS} / 3600`
SS=`expr ${SS} % 3600`
MM=`expr ${SS} / 60`
SS=`expr ${SS} % 60`

echo "Total Time: ${HH}:${MM}:${SS} (h:m:s)"
